export const LOAD_SYMBOLS = 'LOAD_SYMBOLS';
export const CHANGE_TARGET_CURRENCY = 'CHANGE_TARGET_CURRENCY';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';
export const SAVE_CURRENT_RATE = 'SAVE_CURRENT_RATE';
export const CONVERT = 'CONVERT';
